use_frameworks!

platform :ios, '10.0'

target 'FBTabBar_Example' do
  pod 'FBTabBar', :git => 'https://github.com/flybear123/FBTabBar.git'
  
  target 'FBTabBar_Tests' do
    inherit! :search_paths

    
  end
end
